name=GroveDriverPack
version=1.12.0
author=Seeed K.K.
maintainer=matsujirushi
sentence=GroveDriverPack
paragraph=
category=Signal Input/Output
url=https://github.com/SeeedJP/GroveDriverPack/blob/main/readme.md
architectures=Seeed_STM32F4,stm32,SeeedJP_ReButton,samd,nrf52
includes=GroveDriverPack.h
